### ISSUE TITLE
File classname psr-4 standard

### ISSUE THREAD

**Issue by mmerlijn** [gkermer/nova-text-auto-complete#14]
Deprecation Notice: Class Gkermer\TextAutoComplete\TextAutoComplete located in .../vendor/gkermer/nova-text-auto-complete/src\NovaTextAutoComplete.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar

Solution rename filename /src/NovaTextAutoComplete to /src/TextAutoComplete

**Comment by mmerlijn** [comment]
Sorry, I see it's already fixed in new release. Thnx!

**Comment by gkermer** [comment]
Thank you!
