### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mmerlijn** [gkermer/nova-text-auto-complete#15]
Could you make a new release. 
Version 0.04 doesn't contain the PSR-4 fix.

**Comment by clarkewing** [comment]
Up. With the release of Composer 2, tagging a new release would be super useful!

**Comment by niekbr** [comment]
A new version would be appreciated!

**Comment by andrefedalto** [comment]
Thumbs up for this request 👍

**Comment by fsmiamoto** [comment]
Would really appreciate a new release!

**Comment by gkermer** [comment]
Done. Please update.

Thank you for your comments.
