### ISSUE TITLE
Passing additional variable data into the function

### ISSUE THREAD

**Issue by patricktsg** [gkermer/nova-text-auto-complete#3]
I'm using a DB select to search a model, it works fine but I want to pass in the _id of a belongs to so I can return options that are groupedBy 'name', 'some_id' - I can't seem to pass @this->some_id into the scope of the field function trying:

`

            $someId = $this->some_id; // Get some id from the current resource works and dumps '1'

            TextAutoComplete::make('Value', 'name')->items(function($search) use ($someId) {
                dump($someId); // always NULL not getting into the field scope
                return DB::table('products')
                    ->select('name', 'some_id')
                    ->where('some_id', $someId)
                    ->where('name', 'like', '%' . $search . '%')
                    ->groupBy('some_id', 'name')
                    ->get()
                    ->pluck('name');
            })->help('* Enter the value'),
`

**Comment by gkermer** [comment]
Hello,

it should be possible now. Please check out v0.0.3.
